### PR TITLE
fix: shorten links when the common prefix isn't available

### LINKED ISSUE #192: Ability to set source text to file name instead of full path.
**Is your feature request related to a problem? Please describe.**

Unless this is already possible (if so please lmk) I haven't figured out a way to prevent the source text from using the full path.

When I use the jsdoc default theme, it just displays the file name, which is the way I prefer it. The full path on my local machine isn't really relevant when it's displayed using GitHub pages.

**Describe the solution you'd like**

An option to change this behavior to the one I specified above would be preferred.

**Describe alternatives you've considered**

The best solution I've come up with is just not providing the source files all together, however that doesn't feel very end-user friendly.

```json
{
    "markdown": {
        "hardwrap": false,
        "idInHeadings": true
    },
    "templates": {
        "default": {
            "outputSourceFiles": false,
            "staticFiles": {
                "paths": ["tutorials/assets/"]
            }
        }
    },
    "opts": {
        "template": "node_modules/clean-jsdoc-theme"
    }
}
```

**Additional context**

image

### PR DESCRIPTION
**Pull request by jacobhumston-school**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This pull request fixes an issue where having only one file in the source directory causes the source file links to not become shortened. The issue seems to originate from `common-path-prefix`.  (https://github.com/novemberborn/common-path-prefix/blob/ff573979a038f0946ce27498fd1e570489b8f27d/index.js#L15) The solution I came up with was to simply split the path by the default `/` and then get the file name from the last entree of the array. This only occurs if the common prefix is unavailable.

This pull request also includes some formatting changes caused by prettier. However I'll remove them if requested to do so.  

Fixes #192 

## Type of change

Please mark options that is/are relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (if so, then explain below briefly)

### CODE REVIEW

**Comment by ankitskvmdam** [comment]
Wonderful! This is a very nice catch.

I have a different solution, do you it would be nice to show `src/index.js` instead of `index.js`.

**Comment by ankitskvmdam** [comment]
Sure, so let keep the default behaviour then (what JSDoc is doing). So, I dig more into JSdoc code and I found that now they stop using `common-path-prefix`, instead they started using their built in common prefix function.

Do you mind if I update this PR?

**Comment by ankitskvmdam** [comment]
Here is the fix. https://github.com/ankitskvmdam/clean-jsdoc-theme/pull/194

I will publish the new fix soon. Thanks for find the bug, it is really super helpful.

**Comment by jacobhumston-school** [comment]
> Sure, so let keep the default behaviour then (what JSDoc is doing). So, I dig more into JSdoc code and I found that now they stop using `common-path-prefix`, instead they started using their built in common prefix function.
> 
> Do you mind if I update this PR?

That's fine! I appreciate it.

> Here is the fix. #194
> 
> I will publish the new fix soon. Thanks for find the bug, it is really super helpful.

Alright. 👍

**Comment by ankitskvmdam** [comment]
I have published the fix. Please try `clean-jsdoc-theme v4.2.5`. If the issue persist please let me know.
Thanks!

**Comment by jacobhumston-school** [comment]
> I have published the fix. Please try `clean-jsdoc-theme v4.2.5`. If the issue persist please let me know. Thanks!

It's fixed, thank you again! :hugs:

**Pull request closed without merging**
